language: generic 
sudo: required
services:
  - docker
  
before_install:
  - docker build -t k3snoob/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true k3snoob/react-test npm run test  
  
after_success:
  - docker build -t k3snoob/multi-client ./client
  - docker build -t k3snoob/multi-nginx ./nginx
  - docker build -t k3snoob/multi-server ./server
  - docker build -t k3snoob/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push k3snoob/multi-client
  - docker push k3snoob/multi-nginx
  - docker push k3snoob/multi-ser
  - docker push k3snoob/multi-worker
  
 deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-eu-west-1-944429017930
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY